// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAvksfPgWN6alcbPUBkR4-5SYjEkraXw4',
    appId: '1:529488417784:web:076df15a046213db743c0d',
    messagingSenderId: '529488417784',
    projectId: 'keke-comdo-project',
    authDomain: 'keke-comdo-project.firebaseapp.com',
    storageBucket: 'keke-comdo-project.appspot.com',
    measurementId: 'G-V89Z8D8GHS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZc7NL-nbmsTu2gxGQ4dyV8IAk-1hnrVs',
    appId: '1:529488417784:android:a1c72950ef4ca4be743c0d',
    messagingSenderId: '529488417784',
    projectId: 'keke-comdo-project',
    storageBucket: 'keke-comdo-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAT68c7iI0DSsbZaEXys_UOiK-IW9XyT6o',
    appId: '1:529488417784:ios:71a730f07cecb36c743c0d',
    messagingSenderId: '529488417784',
    projectId: 'keke-comdo-project',
    storageBucket: 'keke-comdo-project.appspot.com',
    iosBundleId: 'com.example.pjMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAT68c7iI0DSsbZaEXys_UOiK-IW9XyT6o',
    appId: '1:529488417784:ios:71a730f07cecb36c743c0d',
    messagingSenderId: '529488417784',
    projectId: 'keke-comdo-project',
    storageBucket: 'keke-comdo-project.appspot.com',
    iosBundleId: 'com.example.pjMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAvksfPgWN6alcbPUBkR4-5SYjEkraXw4',
    appId: '1:529488417784:web:75d5b9e8b8b54ee8743c0d',
    messagingSenderId: '529488417784',
    projectId: 'keke-comdo-project',
    authDomain: 'keke-comdo-project.firebaseapp.com',
    storageBucket: 'keke-comdo-project.appspot.com',
    measurementId: 'G-BEGL94PNFJ',
  );
}
